[challenge]
title = "Jumpman"
description = "chall/description.txt"
solution = "^(?i)dnctf(?-i){th3r3_m4y_st1ll_b3_h0p3_5290}$"
points = 400

[download]
files = [ "src/game/levels.c" ]

# NOTE: I HAVE NOT YET SET UP THE NETCAT CHALLENGE W/ DOCKER
[server]
service_name = "jumpman"
service_port = 5507
