version: '3.8'

services:
    sanity-check:
        build: ./misc/sample/chall
        ports:
            - 5500:5000
        privileged: true
    ac:
        build: ./rev/ac/chall
        ports:
            - 5501:5000
        privileged: true
    gophergame:
        build: ./rev/gophergame
        ports:
            - 5502:5000
        privileged: true
