# Category is already implied by the folder it's in

[challenge]
title = "Sanity Check"
description = "chall/description.txt" # keep readme as txt
solution = "^(?i)dnctf(?-i){s4n1ty_ch3ck_2e87s}$" # PROVIDE REGEX
points = 100 # SPECIFY THE NUMBER OF POINTS HERE

[download]
files = [ "chall/password.txt" ]

[server] # note: # of cpus will be limited to 1 on server
service_name = "sanity-check" # this should be the same as what's in docker-compose.yml
service_port = 5500
